/*
 * Copyright (c) 2025, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 * or visit www.oracle.com if you need additional information or have any
 * questions.
 */

/*
 * @test
 * @summary Count classes generated by Carriers
 * @modules java.base/java.lang.runtime
 * @enablePreview true
 * @compile CarriersGeneratedClasses.java
 * @run main/othervm CarriersGeneratedClasses arrayCarriersOverall
 * @run main/othervm CarriersGeneratedClasses arrayCarriersPrint
 * @run main/othervm CarriersGeneratedClasses testGeneratedClassesLimited
 */

import java.lang.invoke.MethodType;
import java.lang.runtime.ArrayCarriers;
import java.util.concurrent.atomic.AtomicInteger;
import jdk.jfr.consumer.RecordedClass;
import jdk.jfr.consumer.RecordedEvent;
import jdk.jfr.consumer.RecordedFrame;
import jdk.jfr.consumer.RecordedStackTrace;
import jdk.jfr.consumer.RecordingStream;

public class CarriersGeneratedClasses {
    private static final String CARRIERS_CLASS = ArrayCarriers.class.getName();

    public static void main(String[] args) throws Throwable {
        switch (args[0]) {
            case "arrayCarriersOverall" -> arrayCarriersOverall();
            case "arrayCarriersPrint" -> arrayCarriersPrint();
            case "testGeneratedClassesLimited" -> testGeneratedClassesLimited();
            default -> throw new AssertionError("Unknown method.");
        }
    }

    static void arrayCarriersOverall() throws Throwable {
        MethodType[] tests = new MethodType[] {
            MethodType.methodType(Object.class),
            MethodType.methodType(Object.class, Object.class),
            MethodType.methodType(Object.class, Object.class, Object.class),
            MethodType.methodType(Object.class, String.class, Object.class),
            MethodType.methodType(Object.class, Object.class, String.class),
            MethodType.methodType(Object.class, Object.class, Object.class, Object.class),
            MethodType.methodType(Object.class, String.class, Object.class, Object.class),
            MethodType.methodType(Object.class, Object.class, String.class, Object.class),
            MethodType.methodType(Object.class, Object.class, String.class, String.class),
            MethodType.methodType(Object.class, int.class, Object.class, Object.class),
            MethodType.methodType(Object.class, Object.class, int.class, Object.class),
            MethodType.methodType(Object.class, Object.class, Object.class, int.class),
            MethodType.methodType(Object.class, int.class, int.class, Object.class),
            MethodType.methodType(Object.class, long.class, int.class, Object.class),
            MethodType.methodType(Object.class, float.class, int.class, Object.class),
            MethodType.methodType(Object.class, double.class, int.class, Object.class),
            MethodType.methodType(Object.class, int.class, double.class, Object.class),
        };


        for (MethodType testCase : tests) {
            System.err.println("running: " + testCase);
            System.err.println("total loaded classes: " + countLoadedClasses(testCase, false));
        }
    }

    static void arrayCarriersPrint() throws Throwable {
        countLoadedClasses(MethodType.methodType(Object.class, Object.class, Object.class), false);
        countLoadedClasses(MethodType.methodType(Object.class, String.class, Object.class), true);
    }

    static void testGeneratedClassesLimited() throws Throwable {
        countLoadedClasses(MethodType.methodType(Object.class, Object.class, Object.class), false);
        countLoadedClasses(MethodType.methodType(Object.class, String.class, Object.class), false);
        assertLoadedClasses(MethodType.methodType(Object.class, Object.class, String.class), 0);

        countLoadedClasses(MethodType.methodType(Object.class, int.class, Object.class), false);
        for (int i = 0; i < 100; i++) {
            assertLoadedClasses(MethodType.methodType(Object.class, int.class, String.class), 0);
        }
    }

    private static void assertLoadedClasses(MethodType testCase, int expectedClasses) {
        int loaded = countLoadedClasses(testCase, false);
        if (loaded != expectedClasses) {
            throw new AssertionError("Unexpected loaded classes, expected " + expectedClasses + ", got: " + loaded);
        }
    }
    private static int countLoadedClasses(MethodType testCase, boolean printTraces) {
        try (var rs = new RecordingStream()) {
            AtomicInteger loadedClasses = new AtomicInteger();

            rs.enable("jdk.ClassLoad");
            rs.onEvent(evt -> {
                RecordedStackTrace trace = evt.getStackTrace();
                boolean important = false;
                if (trace == null) {
                    important = true;
                } else {
                    for (RecordedFrame frame : trace.getFrames()) {
                        if (frame.getMethod().getType().getName().startsWith(CARRIERS_CLASS)) {
                            important = true;
                            break;
                        }
                    }
                }
                if (important) {
                    loadedClasses.incrementAndGet();
                    if (printTraces) {
                        printClassLoadEvent(evt);
                    }
                }
            });

            rs.startAsync();

            ArrayCarriers.initializingConstructor(testCase);

            for (int c = 0; c < testCase.parameterCount(); c++) {
                ArrayCarriers.component(testCase, c);
            }

            rs.stop();

            return loadedClasses.get();
        }
    }

    private static void printClassLoadEvent(RecordedEvent evt) {
        RecordedStackTrace trace = evt.getStackTrace();
        RecordedClass clazz = evt.getClass("loadedClass");
        String className = clazz != null ? clazz.getName() : "<unknown>";

        if (trace == null) {
            System.err.println("loaded: " + className + ", without a trace");
        } else {
            System.err.println("loaded: " + className + ", trace:");
            for (RecordedFrame frame2 : trace.getFrames()) {
                String frameClassName = frame2.getMethod().getType().getName();
                int dot = frameClassName.lastIndexOf('.');
                String simpleName = frameClassName.substring(dot + 1);
                System.err.println("    at " + frameClassName + "." + frame2.getMethod().getName() + "(" + simpleName + ".java:" + frame2.getLineNumber() + ")");
            }
        }
    }
}
